name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:

  docker-build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout source
        uses: actions/checkout@v4


      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build webapp image
        run: docker build --build-arg APP_NAME=webapp -t ghcr.io/adamovick/k8s-dotnet-lab:v3 -f docker/Dockerfile .


      - name: Push webapp image
        run: docker push ghcr.io/adamovick/k8s-dotnet-lab:v3


      - name: Build blog image
        run: docker build --build-arg APP_NAME=blog -t ghcr.io/adamovick/kral-blog:v4 -f docker/Dockerfile .


      - name: Push blog image
        run: docker push ghcr.io/adamovick/kral-blog:v4