name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:

  docker-build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout source
        uses: actions/checkout@v4


      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build Docker image
        run: docker build -t ghcr.io/adamovick/k8s-dotnet-lab:v1 -f docker/Dockerfile .


      - name: Push Docker image
        run: docker push ghcr.io/adamovick/k8s-dotnet-lab:v2